project_id = "xvpwbocwasbtzrzrxyvu"

[functions.chat-ai]
verify_jwt = true

[functions.verify-pi-auth]
verify_jwt = false

[functions.geocode-address]
verify_jwt = true

[functions.pinet-meta]
verify_jwt = false

[functions.list-user-businesses]
verify_jwt = true

[functions.update-pi-price]
verify_jwt = false

[functions.verify-business]
verify_jwt = false

[functions.delete-account]
verify_jwt = false

[functions.cleanup-deleted-accounts]
verify_jwt = false
