/**
 * Maps country names to their ISO 3166-1 alpha-2 codes for LocationIQ API filtering.
 * Includes common variations and alternative names.
 */
export const countryCodeMapping: Record<string, string> = {
  // A
  'afghanistan': 'af',
  'albania': 'al',
  'algeria': 'dz',
  'andorra': 'ad',
  'angola': 'ao',
  'argentina': 'ar',
  'armenia': 'am',
  'australia': 'au',
  'austria': 'at',
  'azerbaijan': 'az',
  
  // B
  'bahamas': 'bs',
  'bahrain': 'bh',
  'bangladesh': 'bd',
  'barbados': 'bb',
  'belarus': 'by',
  'belgium': 'be',
  'belize': 'bz',
  'benin': 'bj',
  'bhutan': 'bt',
  'bolivia': 'bo',
  'bosnia': 'ba',
  'bosnia and herzegovina': 'ba',
  'botswana': 'bw',
  'brazil': 'br',
  'brasil': 'br',
  'brunei': 'bn',
  'bulgaria': 'bg',
  'burkina faso': 'bf',
  'burundi': 'bi',
  
  // C
  'cambodia': 'kh',
  'cameroon': 'cm',
  'canada': 'ca',
  'cape verde': 'cv',
  'central african republic': 'cf',
  'chad': 'td',
  'chile': 'cl',
  'china': 'cn',
  'colombia': 'co',
  'comoros': 'km',
  'congo': 'cg',
  'costa rica': 'cr',
  'croatia': 'hr',
  'cuba': 'cu',
  'cyprus': 'cy',
  'czech republic': 'cz',
  'czechia': 'cz',
  
  // D
  'denmark': 'dk',
  'djibouti': 'dj',
  'dominica': 'dm',
  'dominican republic': 'do',
  
  // E
  'ecuador': 'ec',
  'egypt': 'eg',
  'el salvador': 'sv',
  'equatorial guinea': 'gq',
  'eritrea': 'er',
  'estonia': 'ee',
  'eswatini': 'sz',
  'swaziland': 'sz',
  'ethiopia': 'et',
  
  // F
  'fiji': 'fj',
  'finland': 'fi',
  'france': 'fr',
  
  // G
  'gabon': 'ga',
  'gambia': 'gm',
  'georgia': 'ge',
  'germany': 'de',
  'deutschland': 'de',
  'ghana': 'gh',
  'greece': 'gr',
  'grenada': 'gd',
  'guatemala': 'gt',
  'guinea': 'gn',
  'guinea-bissau': 'gw',
  'guyana': 'gy',
  
  // H
  'haiti': 'ht',
  'honduras': 'hn',
  'hungary': 'hu',
  
  // I
  'iceland': 'is',
  'india': 'in',
  'indonesia': 'id',
  'iran': 'ir',
  'iraq': 'iq',
  'ireland': 'ie',
  'israel': 'il',
  'italy': 'it',
  'italia': 'it',
  'ivory coast': 'ci',
  "côte d'ivoire": 'ci',
  
  // J
  'jamaica': 'jm',
  'japan': 'jp',
  'jordan': 'jo',
  
  // K
  'kazakhstan': 'kz',
  'kenya': 'ke',
  'kiribati': 'ki',
  'north korea': 'kp',
  'south korea': 'kr',
  'korea': 'kr',
  'kuwait': 'kw',
  'kyrgyzstan': 'kg',
  
  // L
  'laos': 'la',
  'latvia': 'lv',
  'lebanon': 'lb',
  'lesotho': 'ls',
  'liberia': 'lr',
  'libya': 'ly',
  'liechtenstein': 'li',
  'lithuania': 'lt',
  'luxembourg': 'lu',
  
  // M
  'madagascar': 'mg',
  'malawi': 'mw',
  'malaysia': 'my',
  'maldives': 'mv',
  'mali': 'ml',
  'malta': 'mt',
  'marshall islands': 'mh',
  'mauritania': 'mr',
  'mauritius': 'mu',
  'mexico': 'mx',
  'méxico': 'mx',
  'micronesia': 'fm',
  'moldova': 'md',
  'monaco': 'mc',
  'mongolia': 'mn',
  'montenegro': 'me',
  'morocco': 'ma',
  'mozambique': 'mz',
  'myanmar': 'mm',
  'burma': 'mm',
  
  // N
  'namibia': 'na',
  'nauru': 'nr',
  'nepal': 'np',
  'netherlands': 'nl',
  'holland': 'nl',
  'new zealand': 'nz',
  'nicaragua': 'ni',
  'niger': 'ne',
  'nigeria': 'ng',
  'north macedonia': 'mk',
  'macedonia': 'mk',
  'norway': 'no',
  
  // O
  'oman': 'om',
  
  // P
  'pakistan': 'pk',
  'palau': 'pw',
  'palestine': 'ps',
  'panama': 'pa',
  'papua new guinea': 'pg',
  'paraguay': 'py',
  'peru': 'pe',
  'philippines': 'ph',
  'poland': 'pl',
  'polska': 'pl',
  'portugal': 'pt',
  
  // Q
  'qatar': 'qa',
  
  // R
  'romania': 'ro',
  'russia': 'ru',
  'russian federation': 'ru',
  'rwanda': 'rw',
  
  // S
  'saint kitts and nevis': 'kn',
  'saint lucia': 'lc',
  'saint vincent': 'vc',
  'samoa': 'ws',
  'san marino': 'sm',
  'sao tome and principe': 'st',
  'saudi arabia': 'sa',
  'senegal': 'sn',
  'serbia': 'rs',
  'seychelles': 'sc',
  'sierra leone': 'sl',
  'singapore': 'sg',
  'slovakia': 'sk',
  'slovenia': 'si',
  'solomon islands': 'sb',
  'somalia': 'so',
  'south africa': 'za',
  'south sudan': 'ss',
  'spain': 'es',
  'españa': 'es',
  'sri lanka': 'lk',
  'sudan': 'sd',
  'suriname': 'sr',
  'sweden': 'se',
  'switzerland': 'ch',
  'syria': 'sy',
  
  // T
  'taiwan': 'tw',
  'tajikistan': 'tj',
  'tanzania': 'tz',
  'thailand': 'th',
  'timor-leste': 'tl',
  'east timor': 'tl',
  'togo': 'tg',
  'tonga': 'to',
  'trinidad and tobago': 'tt',
  'tunisia': 'tn',
  'turkey': 'tr',
  'türkiye': 'tr',
  'turkmenistan': 'tm',
  'tuvalu': 'tv',
  
  // U
  'uganda': 'ug',
  'ukraine': 'ua',
  'united arab emirates': 'ae',
  'uae': 'ae',
  'united kingdom': 'gb',
  'uk': 'gb',
  'great britain': 'gb',
  'england': 'gb',
  'scotland': 'gb',
  'wales': 'gb',
  'united states': 'us',
  'united states of america': 'us',
  'usa': 'us',
  'us': 'us',
  'america': 'us',
  'uruguay': 'uy',
  'uzbekistan': 'uz',
  
  // V
  'vanuatu': 'vu',
  'vatican': 'va',
  'vatican city': 'va',
  'venezuela': 've',
  'vietnam': 'vn',
  'viet nam': 'vn',
  
  // Y
  'yemen': 'ye',
  
  // Z
  'zambia': 'zm',
  'zimbabwe': 'zw',
};

/**
 * Converts a country name to its ISO 3166-1 alpha-2 code.
 * Returns undefined if the country is not found.
 */
export function getCountryCode(countryName: string): string | undefined {
  if (!countryName) return undefined;
  
  const normalized = countryName.toLowerCase().trim();
  return countryCodeMapping[normalized];
}

/**
 * Gets country name from ISO code.
 */
export function getCountryName(code: string): string | undefined {
  if (!code) return undefined;
  const normalizedCode = code.toLowerCase();
  
  // Find the first entry with this code
  for (const [name, countryCode] of Object.entries(countryCodeMapping)) {
    if (countryCode === normalizedCode) {
      // Return a properly capitalized version
      return name.split(' ').map(word => 
        word.charAt(0).toUpperCase() + word.slice(1)
      ).join(' ');
    }
  }
  return undefined;
}

/**
 * Complete list of all countries for the searchable dropdown.
 * Sorted alphabetically.
 */
export const allCountries = [
  { name: 'Afghanistan', code: 'af' },
  { name: 'Albania', code: 'al' },
  { name: 'Algeria', code: 'dz' },
  { name: 'Andorra', code: 'ad' },
  { name: 'Angola', code: 'ao' },
  { name: 'Argentina', code: 'ar' },
  { name: 'Armenia', code: 'am' },
  { name: 'Australia', code: 'au' },
  { name: 'Austria', code: 'at' },
  { name: 'Azerbaijan', code: 'az' },
  { name: 'Bahamas', code: 'bs' },
  { name: 'Bahrain', code: 'bh' },
  { name: 'Bangladesh', code: 'bd' },
  { name: 'Barbados', code: 'bb' },
  { name: 'Belarus', code: 'by' },
  { name: 'Belgium', code: 'be' },
  { name: 'Belize', code: 'bz' },
  { name: 'Benin', code: 'bj' },
  { name: 'Bhutan', code: 'bt' },
  { name: 'Bolivia', code: 'bo' },
  { name: 'Bosnia and Herzegovina', code: 'ba' },
  { name: 'Botswana', code: 'bw' },
  { name: 'Brazil', code: 'br' },
  { name: 'Brunei', code: 'bn' },
  { name: 'Bulgaria', code: 'bg' },
  { name: 'Burkina Faso', code: 'bf' },
  { name: 'Burundi', code: 'bi' },
  { name: 'Cambodia', code: 'kh' },
  { name: 'Cameroon', code: 'cm' },
  { name: 'Canada', code: 'ca' },
  { name: 'Cape Verde', code: 'cv' },
  { name: 'Central African Republic', code: 'cf' },
  { name: 'Chad', code: 'td' },
  { name: 'Chile', code: 'cl' },
  { name: 'China', code: 'cn' },
  { name: 'Colombia', code: 'co' },
  { name: 'Comoros', code: 'km' },
  { name: 'Congo', code: 'cg' },
  { name: 'Costa Rica', code: 'cr' },
  { name: 'Croatia', code: 'hr' },
  { name: 'Cuba', code: 'cu' },
  { name: 'Cyprus', code: 'cy' },
  { name: 'Czech Republic', code: 'cz' },
  { name: 'Denmark', code: 'dk' },
  { name: 'Djibouti', code: 'dj' },
  { name: 'Dominica', code: 'dm' },
  { name: 'Dominican Republic', code: 'do' },
  { name: 'Ecuador', code: 'ec' },
  { name: 'Egypt', code: 'eg' },
  { name: 'El Salvador', code: 'sv' },
  { name: 'Equatorial Guinea', code: 'gq' },
  { name: 'Eritrea', code: 'er' },
  { name: 'Estonia', code: 'ee' },
  { name: 'Eswatini', code: 'sz' },
  { name: 'Ethiopia', code: 'et' },
  { name: 'Fiji', code: 'fj' },
  { name: 'Finland', code: 'fi' },
  { name: 'France', code: 'fr' },
  { name: 'Gabon', code: 'ga' },
  { name: 'Gambia', code: 'gm' },
  { name: 'Georgia', code: 'ge' },
  { name: 'Germany', code: 'de' },
  { name: 'Ghana', code: 'gh' },
  { name: 'Greece', code: 'gr' },
  { name: 'Grenada', code: 'gd' },
  { name: 'Guatemala', code: 'gt' },
  { name: 'Guinea', code: 'gn' },
  { name: 'Guinea-Bissau', code: 'gw' },
  { name: 'Guyana', code: 'gy' },
  { name: 'Haiti', code: 'ht' },
  { name: 'Honduras', code: 'hn' },
  { name: 'Hungary', code: 'hu' },
  { name: 'Iceland', code: 'is' },
  { name: 'India', code: 'in' },
  { name: 'Indonesia', code: 'id' },
  { name: 'Iran', code: 'ir' },
  { name: 'Iraq', code: 'iq' },
  { name: 'Ireland', code: 'ie' },
  { name: 'Israel', code: 'il' },
  { name: 'Italy', code: 'it' },
  { name: 'Jamaica', code: 'jm' },
  { name: 'Japan', code: 'jp' },
  { name: 'Jordan', code: 'jo' },
  { name: 'Kazakhstan', code: 'kz' },
  { name: 'Kenya', code: 'ke' },
  { name: 'Kiribati', code: 'ki' },
  { name: 'Kuwait', code: 'kw' },
  { name: 'Kyrgyzstan', code: 'kg' },
  { name: 'Laos', code: 'la' },
  { name: 'Latvia', code: 'lv' },
  { name: 'Lebanon', code: 'lb' },
  { name: 'Lesotho', code: 'ls' },
  { name: 'Liberia', code: 'lr' },
  { name: 'Libya', code: 'ly' },
  { name: 'Liechtenstein', code: 'li' },
  { name: 'Lithuania', code: 'lt' },
  { name: 'Luxembourg', code: 'lu' },
  { name: 'Madagascar', code: 'mg' },
  { name: 'Malawi', code: 'mw' },
  { name: 'Malaysia', code: 'my' },
  { name: 'Maldives', code: 'mv' },
  { name: 'Mali', code: 'ml' },
  { name: 'Malta', code: 'mt' },
  { name: 'Marshall Islands', code: 'mh' },
  { name: 'Mauritania', code: 'mr' },
  { name: 'Mauritius', code: 'mu' },
  { name: 'Mexico', code: 'mx' },
  { name: 'Micronesia', code: 'fm' },
  { name: 'Moldova', code: 'md' },
  { name: 'Monaco', code: 'mc' },
  { name: 'Mongolia', code: 'mn' },
  { name: 'Montenegro', code: 'me' },
  { name: 'Morocco', code: 'ma' },
  { name: 'Mozambique', code: 'mz' },
  { name: 'Myanmar', code: 'mm' },
  { name: 'Namibia', code: 'na' },
  { name: 'Nauru', code: 'nr' },
  { name: 'Nepal', code: 'np' },
  { name: 'Netherlands', code: 'nl' },
  { name: 'New Zealand', code: 'nz' },
  { name: 'Nicaragua', code: 'ni' },
  { name: 'Niger', code: 'ne' },
  { name: 'Nigeria', code: 'ng' },
  { name: 'North Korea', code: 'kp' },
  { name: 'North Macedonia', code: 'mk' },
  { name: 'Norway', code: 'no' },
  { name: 'Oman', code: 'om' },
  { name: 'Pakistan', code: 'pk' },
  { name: 'Palau', code: 'pw' },
  { name: 'Palestine', code: 'ps' },
  { name: 'Panama', code: 'pa' },
  { name: 'Papua New Guinea', code: 'pg' },
  { name: 'Paraguay', code: 'py' },
  { name: 'Peru', code: 'pe' },
  { name: 'Philippines', code: 'ph' },
  { name: 'Poland', code: 'pl' },
  { name: 'Portugal', code: 'pt' },
  { name: 'Qatar', code: 'qa' },
  { name: 'Romania', code: 'ro' },
  { name: 'Russia', code: 'ru' },
  { name: 'Rwanda', code: 'rw' },
  { name: 'Saint Kitts and Nevis', code: 'kn' },
  { name: 'Saint Lucia', code: 'lc' },
  { name: 'Saint Vincent', code: 'vc' },
  { name: 'Samoa', code: 'ws' },
  { name: 'San Marino', code: 'sm' },
  { name: 'Sao Tome and Principe', code: 'st' },
  { name: 'Saudi Arabia', code: 'sa' },
  { name: 'Senegal', code: 'sn' },
  { name: 'Serbia', code: 'rs' },
  { name: 'Seychelles', code: 'sc' },
  { name: 'Sierra Leone', code: 'sl' },
  { name: 'Singapore', code: 'sg' },
  { name: 'Slovakia', code: 'sk' },
  { name: 'Slovenia', code: 'si' },
  { name: 'Solomon Islands', code: 'sb' },
  { name: 'Somalia', code: 'so' },
  { name: 'South Africa', code: 'za' },
  { name: 'South Korea', code: 'kr' },
  { name: 'South Sudan', code: 'ss' },
  { name: 'Spain', code: 'es' },
  { name: 'Sri Lanka', code: 'lk' },
  { name: 'Sudan', code: 'sd' },
  { name: 'Suriname', code: 'sr' },
  { name: 'Sweden', code: 'se' },
  { name: 'Switzerland', code: 'ch' },
  { name: 'Syria', code: 'sy' },
  { name: 'Taiwan', code: 'tw' },
  { name: 'Tajikistan', code: 'tj' },
  { name: 'Tanzania', code: 'tz' },
  { name: 'Thailand', code: 'th' },
  { name: 'Timor-Leste', code: 'tl' },
  { name: 'Togo', code: 'tg' },
  { name: 'Tonga', code: 'to' },
  { name: 'Trinidad and Tobago', code: 'tt' },
  { name: 'Tunisia', code: 'tn' },
  { name: 'Turkey', code: 'tr' },
  { name: 'Turkmenistan', code: 'tm' },
  { name: 'Tuvalu', code: 'tv' },
  { name: 'Uganda', code: 'ug' },
  { name: 'Ukraine', code: 'ua' },
  { name: 'United Arab Emirates', code: 'ae' },
  { name: 'United Kingdom', code: 'gb' },
  { name: 'United States', code: 'us' },
  { name: 'Uruguay', code: 'uy' },
  { name: 'Uzbekistan', code: 'uz' },
  { name: 'Vanuatu', code: 'vu' },
  { name: 'Vatican City', code: 'va' },
  { name: 'Venezuela', code: 've' },
  { name: 'Vietnam', code: 'vn' },
  { name: 'Yemen', code: 'ye' },
  { name: 'Zambia', code: 'zm' },
  { name: 'Zimbabwe', code: 'zw' },
];

/**
 * List of common countries for quick selection (shown at top of list).
 */
export const commonCountries = [
  { name: 'United States', code: 'us' },
  { name: 'Canada', code: 'ca' },
  { name: 'United Kingdom', code: 'gb' },
  { name: 'Australia', code: 'au' },
  { name: 'Germany', code: 'de' },
  { name: 'France', code: 'fr' },
  { name: 'India', code: 'in' },
  { name: 'Brazil', code: 'br' },
  { name: 'South Africa', code: 'za' },
  { name: 'Nigeria', code: 'ng' },
];
