/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as CommuniconRouteImport } from './routes/communicon'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as NotificationAdminRouteImport } from './routes/notification-admin'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RegisteredBusinessRouteImport } from './routes/registered-business'
import { Route as RegistrationRouteImport } from './routes/registration'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VerificationInfoRouteImport } from './routes/verification-info'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as RecommendationsIndexRouteImport } from './routes/recommendations/index'
import { Route as RecommendationsPlaceIdRouteImport } from './routes/recommendations/$placeId'
import { Route as ReviewIndexRouteImport } from './routes/review/index'
import { Route as ReviewBusinessIdRouteImport } from './routes/review/$businessId'
import { Route as UpdateRegistrationIndexRouteImport } from './routes/update-registration/index'
import { Route as UpdateRegistrationBusinessIdRouteImport } from './routes/update-registration/$businessId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const CommuniconRoute = CommuniconRouteImport.update({
  id: '/communicon',
  path: '/communicon',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationAdminRoute = NotificationAdminRouteImport.update({
  id: '/notification-admin',
  path: '/notification-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisteredBusinessRoute = RegisteredBusinessRouteImport.update({
  id: '/registered-business',
  path: '/registered-business',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationRoute = RegistrationRouteImport.update({
  id: '/registration',
  path: '/registration',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificationInfoRoute = VerificationInfoRouteImport.update({
  id: '/verification-info',
  path: '/verification-info',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsIndexRoute = RecommendationsIndexRouteImport.update({
  id: '/recommendations/',
  path: '/recommendations/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsPlaceIdRoute = RecommendationsPlaceIdRouteImport.update({
  id: '/recommendations/$placeId',
  path: '/recommendations/$placeId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewIndexRoute = ReviewIndexRouteImport.update({
  id: '/review/',
  path: '/review/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewBusinessIdRoute = ReviewBusinessIdRouteImport.update({
  id: '/review/$businessId',
  path: '/review/$businessId',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdateRegistrationIndexRoute = UpdateRegistrationIndexRouteImport.update({
  id: '/update-registration/',
  path: '/update-registration/',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdateRegistrationBusinessIdRoute =
  UpdateRegistrationBusinessIdRouteImport.update({
    id: '/update-registration/$businessId',
    path: '/update-registration/$businessId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analytics': typeof AnalyticsRoute
  '/bookmarks': typeof BookmarksRoute
  '/communicon': typeof CommuniconRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/notification-admin': typeof NotificationAdminRoute
  '/notifications': typeof NotificationsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/registered-business': typeof RegisteredBusinessRoute
  '/registration': typeof RegistrationRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/verification-info': typeof VerificationInfoRoute
  '/wallet': typeof WalletRoute
  '/recommendations/$placeId': typeof RecommendationsPlaceIdRoute
  '/review/$businessId': typeof ReviewBusinessIdRoute
  '/update-registration/$businessId': typeof UpdateRegistrationBusinessIdRoute
  '/recommendations/': typeof RecommendationsIndexRoute
  '/review/': typeof ReviewIndexRoute
  '/update-registration/': typeof UpdateRegistrationIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analytics': typeof AnalyticsRoute
  '/bookmarks': typeof BookmarksRoute
  '/communicon': typeof CommuniconRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/notification-admin': typeof NotificationAdminRoute
  '/notifications': typeof NotificationsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/registered-business': typeof RegisteredBusinessRoute
  '/registration': typeof RegistrationRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/verification-info': typeof VerificationInfoRoute
  '/wallet': typeof WalletRoute
  '/recommendations/$placeId': typeof RecommendationsPlaceIdRoute
  '/review/$businessId': typeof ReviewBusinessIdRoute
  '/update-registration/$businessId': typeof UpdateRegistrationBusinessIdRoute
  '/recommendations': typeof RecommendationsIndexRoute
  '/review': typeof ReviewIndexRoute
  '/update-registration': typeof UpdateRegistrationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analytics': typeof AnalyticsRoute
  '/bookmarks': typeof BookmarksRoute
  '/communicon': typeof CommuniconRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/notification-admin': typeof NotificationAdminRoute
  '/notifications': typeof NotificationsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/registered-business': typeof RegisteredBusinessRoute
  '/registration': typeof RegistrationRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/verification-info': typeof VerificationInfoRoute
  '/wallet': typeof WalletRoute
  '/recommendations/$placeId': typeof RecommendationsPlaceIdRoute
  '/review/$businessId': typeof ReviewBusinessIdRoute
  '/update-registration/$businessId': typeof UpdateRegistrationBusinessIdRoute
  '/recommendations/': typeof RecommendationsIndexRoute
  '/review/': typeof ReviewIndexRoute
  '/update-registration/': typeof UpdateRegistrationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/analytics'
    | '/bookmarks'
    | '/communicon'
    | '/contact'
    | '/cookies'
    | '/notification-admin'
    | '/notifications'
    | '/pricing'
    | '/privacy'
    | '/registered-business'
    | '/registration'
    | '/settings'
    | '/terms'
    | '/verification-info'
    | '/wallet'
    | '/recommendations/$placeId'
    | '/review/$businessId'
    | '/update-registration/$businessId'
    | '/recommendations/'
    | '/review/'
    | '/update-registration/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/analytics'
    | '/bookmarks'
    | '/communicon'
    | '/contact'
    | '/cookies'
    | '/notification-admin'
    | '/notifications'
    | '/pricing'
    | '/privacy'
    | '/registered-business'
    | '/registration'
    | '/settings'
    | '/terms'
    | '/verification-info'
    | '/wallet'
    | '/recommendations/$placeId'
    | '/review/$businessId'
    | '/update-registration/$businessId'
    | '/recommendations'
    | '/review'
    | '/update-registration'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/analytics'
    | '/bookmarks'
    | '/communicon'
    | '/contact'
    | '/cookies'
    | '/notification-admin'
    | '/notifications'
    | '/pricing'
    | '/privacy'
    | '/registered-business'
    | '/registration'
    | '/settings'
    | '/terms'
    | '/verification-info'
    | '/wallet'
    | '/recommendations/$placeId'
    | '/review/$businessId'
    | '/update-registration/$businessId'
    | '/recommendations/'
    | '/review/'
    | '/update-registration/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BookmarksRoute: typeof BookmarksRoute
  CommuniconRoute: typeof CommuniconRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  NotificationAdminRoute: typeof NotificationAdminRoute
  NotificationsRoute: typeof NotificationsRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisteredBusinessRoute: typeof RegisteredBusinessRoute
  RegistrationRoute: typeof RegistrationRoute
  SettingsRoute: typeof SettingsRoute
  TermsRoute: typeof TermsRoute
  VerificationInfoRoute: typeof VerificationInfoRoute
  WalletRoute: typeof WalletRoute
  RecommendationsPlaceIdRoute: typeof RecommendationsPlaceIdRoute
  ReviewBusinessIdRoute: typeof ReviewBusinessIdRoute
  UpdateRegistrationBusinessIdRoute: typeof UpdateRegistrationBusinessIdRoute
  RecommendationsIndexRoute: typeof RecommendationsIndexRoute
  ReviewIndexRoute: typeof ReviewIndexRoute
  UpdateRegistrationIndexRoute: typeof UpdateRegistrationIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communicon': {
      id: '/communicon'
      path: '/communicon'
      fullPath: '/communicon'
      preLoaderRoute: typeof CommuniconRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notification-admin': {
      id: '/notification-admin'
      path: '/notification-admin'
      fullPath: '/notification-admin'
      preLoaderRoute: typeof NotificationAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registered-business': {
      id: '/registered-business'
      path: '/registered-business'
      fullPath: '/registered-business'
      preLoaderRoute: typeof RegisteredBusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registration': {
      id: '/registration'
      path: '/registration'
      fullPath: '/registration'
      preLoaderRoute: typeof RegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verification-info': {
      id: '/verification-info'
      path: '/verification-info'
      fullPath: '/verification-info'
      preLoaderRoute: typeof VerificationInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations/': {
      id: '/recommendations/'
      path: '/recommendations'
      fullPath: '/recommendations/'
      preLoaderRoute: typeof RecommendationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations/$placeId': {
      id: '/recommendations/$placeId'
      path: '/recommendations/$placeId'
      fullPath: '/recommendations/$placeId'
      preLoaderRoute: typeof RecommendationsPlaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/': {
      id: '/review/'
      path: '/review'
      fullPath: '/review/'
      preLoaderRoute: typeof ReviewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/$businessId': {
      id: '/review/$businessId'
      path: '/review/$businessId'
      fullPath: '/review/$businessId'
      preLoaderRoute: typeof ReviewBusinessIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/update-registration/': {
      id: '/update-registration/'
      path: '/update-registration'
      fullPath: '/update-registration/'
      preLoaderRoute: typeof UpdateRegistrationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/update-registration/$businessId': {
      id: '/update-registration/$businessId'
      path: '/update-registration/$businessId'
      fullPath: '/update-registration/$businessId'
      preLoaderRoute: typeof UpdateRegistrationBusinessIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AnalyticsRoute: AnalyticsRoute,
  BookmarksRoute: BookmarksRoute,
  CommuniconRoute: CommuniconRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  NotificationAdminRoute: NotificationAdminRoute,
  NotificationsRoute: NotificationsRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RegisteredBusinessRoute: RegisteredBusinessRoute,
  RegistrationRoute: RegistrationRoute,
  SettingsRoute: SettingsRoute,
  TermsRoute: TermsRoute,
  VerificationInfoRoute: VerificationInfoRoute,
  WalletRoute: WalletRoute,
  RecommendationsPlaceIdRoute: RecommendationsPlaceIdRoute,
  ReviewBusinessIdRoute: ReviewBusinessIdRoute,
  UpdateRegistrationBusinessIdRoute: UpdateRegistrationBusinessIdRoute,
  RecommendationsIndexRoute: RecommendationsIndexRoute,
  ReviewIndexRoute: ReviewIndexRoute,
  UpdateRegistrationIndexRoute: UpdateRegistrationIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
