-- Insert a mock business for the Developer account
INSERT INTO businesses (
  owner_id,
  name,
  description,
  category,
  street_address,
  city,
  state,
  postal_code,
  country,
  coordinates,
  business_types,
  keywords,
  is_certified,
  is_verified,
  verification_status,
  contact_info,
  hours,
  pi_wallet_address
) VALUES (
  '00000000-0000-0000-0000-000000000001',
  'Pi Network Cafe',
  'A cozy cafe accepting Pi cryptocurrency payments. Enjoy premium coffee, fresh pastries, and a welcoming atmosphere in the heart of San Francisco.',
  'Restaurant',
  '123 Blockchain Avenue',
  'San Francisco',
  'California',
  '94102',
  'US',
  '37.7749,-122.4194',
  ARRAY['cafe', 'restaurant', 'coffee shop'],
  ARRAY['coffee', 'cafe', 'pi payments', 'cryptocurrency', 'breakfast', 'lunch', 'pastries'],
  true,
  true,
  'verified',
  '{"phone": "+1-555-0123", "email": "contact@pinetworkcafe.com", "website": "https://pinetworkcafe.com", "firstName": "John", "lastName": "Developer"}'::jsonb,
  '{"monday": {"open": "07:00", "close": "19:00"}, "tuesday": {"open": "07:00", "close": "19:00"}, "wednesday": {"open": "07:00", "close": "19:00"}, "thursday": {"open": "07:00", "close": "19:00"}, "friday": {"open": "07:00", "close": "21:00"}, "saturday": {"open": "08:00", "close": "21:00"}, "sunday": {"open": "08:00", "close": "18:00"}}'::jsonb,
  'GDRM3MK6KMHAUAJEQ5UAI5KF6PNMQXQ5BJEQT7VR3T5TQRV5TQRV'
);